CREATE TABLE guilds (
    id varchar(255) NOT NULL,
    afk_channel_id varchar(255) NULL,
    afk_timeout int NULL,
    banner varchar(255) NULL,
    default_message_notifications int NULL,
    description varchar(255) NULL,
    discovery_splash varchar(255) NULL,
    explicit_content_filter int NULL,
    features text NOT NULL,
    primary_category_id int NULL,
    icon varchar(255) NULL,
    large tinyint NULL,
    max_members int NULL,
    max_presences int NULL,
    max_video_channel_users int NULL,
    member_count int NULL,
    presence_count int NULL,
    template_id varchar(255) NULL,
    mfa_level int NULL,
    name varchar(255) NOT NULL,
    owner_id varchar(255) NULL,
    preferred_locale varchar(255) NULL,
    premium_subscription_count int NULL,
    premium_tier int NULL,
    public_updates_channel_id varchar(255) NULL,
    rules_channel_id varchar(255) NULL,
    region varchar(255) NULL,
    splash varchar(255) NULL,
    system_channel_id varchar(255) NULL,
    system_channel_flags int NULL,
    unavailable tinyint NULL,
    verification_level int NULL,
    welcome_screen text NOT NULL,
    widget_channel_id varchar(255) NULL,
    widget_enabled tinyint NULL,
    nsfw_level int NULL,
    nsfw tinyint NULL,
    parent varchar(255) NULL,

    premium_progress_bar_enabled tinyint NULL,

    PRIMARY KEY (id)
) ENGINE = InnoDB