CREATE TABLE users (
    id varchar(255) NOT NULL,
    username varchar(255) NOT NULL,
    discriminator varchar(255) NOT NULL,
    avatar varchar(255) NULL,
    accent_color int NULL,
    banner varchar(255) NULL,
    phone varchar(255) NULL,
    desktop tinyint NOT NULL,
    mobile tinyint NOT NULL,
    premium tinyint NOT NULL,
    premium_type int NOT NULL,
    bot tinyint NOT NULL,
    bio varchar(255) NULL,
    _system tinyint NOT NULL,
    nsfw_allowed tinyint NOT NULL,
    mfa_enabled tinyint NULL,
    totp_secret varchar(255) NULL,
    totp_last_ticket varchar(255) NULL,
    created_at datetime NOT NULL,
    premium_since datetime NULL,
    verified tinyint NOT NULL,
    disabled tinyint NOT NULL,
    deleted tinyint NOT NULL,
    email varchar(255) NULL,
    flags varchar(255) NOT NULL,
    public_flags int NOT NULL,
    rights bigint NOT NULL,
    data text NOT NULL,
    fingerprints text NOT NULL,
    extended_settings text NOT NULL,

    settings_id varchar(255) NULL,

    UNIQUE INDEX IDX_76ba283779c8441fd5ff819c8c (settings_id),
    UNIQUE INDEX REL_76ba283779c8441fd5ff819c8c (settings_id),
    PRIMARY KEY (id)
) ENGINE = InnoDB